.PHONY all:
all:
	gcc -Wall -DPART1 csc360a3.c -o diskinfo
	gcc -Wall -DPART2 csc360a3.c -o disklist
	gcc -Wall -DPART3 csc360a3.c -o diskget
	gcc -Wall -DPART4 csc360a3.c -o diskput

.PHONY clean:
clean:
	-rm diskinfo disklist distget diskput
